const AQCA_ALGORITHMS = {
    "shor": {
        id: "shor",
        name: "Shor's Algorithm",
        category: "Flagship & Hybrid",
        
        // 1. Comparison Metrics
        problem: "Integer factorization & discrete logarithms",
        math: "Modular exponentiation & Quantum Fourier Transform",
        timeQuantum: "O((log N)^3)",
        timeClassical: "O(e^{1.9 (log N)^{1/3} (log log N)^{2/3}})",
        spaceQuantum: "O(log N)",
        spaceClassical: "O(log N)",
        classicalEq: "General Number Field Sieve (GNFS)",
        qubitsReq: "2n + 1 (logical)",
        depth: "O(n^3)",
        oracle: false,
        qft: true,
        qpe: true,
        applications: ["Cryptography breaking (RSA)", "Elliptic Curve cryptography"],
        advantages: ["Exponential speedup", "Solves classically intractable problem"],
        limitations: ["Requires perfect fault-tolerance", "Massive circuit depth"],

        // 2. Performance Metrics
        speedupType: "Exponential",
        gateCount: "O(n^3)",
        scalingFnQ: (n) => Math.pow(Math.log2(n), 3),
        scalingFnC: (n) => Math.exp(1.9 * Math.pow(Math.log2(n), 1/3) * Math.pow(Math.log2(Math.log2(n)), 2/3)),

        // 3. Hardware Compatibility
        ibm: "Low (Too deep for NISQ)",
        ionq: "Low (Limited logical qubits)",
        quantinuum: "Medium (Good for toy models)",
        rigetti: "Low",
        nativeGates: "CX, CP, U3",
        minLogical: "2n+1",
        estPhysical: "1,000,000+",
        nisq: "Infeasible",
        faultTolerant: "Ready (Standard)"
    },
    "grover": {
        id: "grover",
        name: "Grover's Search",
        category: "Phase & Amplitude",
        
        problem: "Unstructured database search",
        math: "Amplitude Amplification & Inversion about Mean",
        timeQuantum: "O(√N)",
        timeClassical: "O(N)",
        spaceQuantum: "O(log N)",
        spaceClassical: "O(1)",
        classicalEq: "Linear Search",
        qubitsReq: "n (logical)",
        depth: "O(√N)",
        oracle: true,
        qft: false,
        qpe: false,
        applications: ["Database search", "SAT Solvers", "Collision finding"],
        advantages: ["Provably optimal for unstructured search", "Broadly applicable"],
        limitations: ["Speedup is only polynomial", "Serial bottleneck"],

        speedupType: "Polynomial (Quadratic)",
        gateCount: "O(√N * n)",
        scalingFnQ: (n) => Math.sqrt(n),
        scalingFnC: (n) => n,

        ibm: "High (for n < 10)",
        ionq: "High (Excellent connectivity)",
        quantinuum: "High",
        rigetti: "Medium",
        nativeGates: "MCX, H, X",
        minLogical: "n + 1 (ancilla)",
        estPhysical: "10,000+",
        nisq: "Challenging (Deep for large N)",
        faultTolerant: "Ready"
    },
    "vqe": {
        id: "vqe",
        name: "Variational Quantum Eigensolver (VQE)",
        category: "Flagship & Hybrid",
        
        problem: "Finding the ground state energy of a Hamiltonian",
        math: "Ritz Variational Principle & Parameterized Ansatz",
        timeQuantum: "O(Poly(N)) * classical loop",
        timeClassical: "O(2^N) (Exact Diagonalization)",
        spaceQuantum: "O(N)",
        spaceClassical: "O(2^N) for exact",
        classicalEq: "Density Matrix Renormalization Group (DMRG)",
        qubitsReq: "N (physical mapped)",
        depth: "Shallow (O(p))",
        oracle: false,
        qft: false,
        qpe: false,
        applications: ["Quantum Chemistry", "Material Science", "Molecular simulation"],
        advantages: ["Noise resilient", "Shallow circuits", "NISQ native"],
        limitations: ["Barren plateaus", "Classical optimizer bottleneck"],

        speedupType: "Heuristic (potentially Exponential)",
        gateCount: "O(N * p)",
        scalingFnQ: (n) => n * n, // Proxy for poly
        scalingFnC: (n) => Math.pow(2, n),

        ibm: "Very High (Native support)",
        ionq: "Very High",
        quantinuum: "Very High",
        rigetti: "Very High",
        nativeGates: "RX, RY, RZ, CX (Hardware native)",
        minLogical: "N/A (Uses physical)",
        estPhysical: "10 - 100+",
        nisq: "Perfect Candidate",
        faultTolerant: "Requires Adaptation"
    },
    "qft": {
        id: "qft",
        name: "Quantum Fourier Transform (QFT)",
        category: "Phase & Amplitude",
        
        problem: "Basis transformation from computational to Fourier",
        math: "Discrete Fourier Transform on amplitudes",
        timeQuantum: "O(n^2)",
        timeClassical: "O(n 2^n) (Fast Fourier Transform)",
        spaceQuantum: "O(n)",
        spaceClassical: "O(2^n)",
        classicalEq: "Fast Fourier Transform (FFT)",
        qubitsReq: "n",
        depth: "O(n)",
        oracle: false,
        qft: true,
        qpe: false,
        applications: ["Subroutine for Shor's", "Subroutine for QPE"],
        advantages: ["Exponential improvement over FFT in runtime"],
        limitations: ["Does not yield classical probability distribution directly"],

        speedupType: "Exponential",
        gateCount: "O(n^2)",
        scalingFnQ: (n) => Math.pow(Math.log2(n), 2),
        scalingFnC: (n) => n * Math.log2(n), // FFT on 2^n space

        ibm: "Medium (Requires all-to-all or swapping)",
        ionq: "High (All-to-all native)",
        quantinuum: "High (QCCD architecture)",
        rigetti: "Low",
        nativeGates: "H, CP (Controlled Phase)",
        minLogical: "n",
        estPhysical: "Varies depending on precision",
        nisq: "Limited (Phase errors accumulate)",
        faultTolerant: "Subroutine Ready"
    },
    "deutsch_jozsa": {
        id: "deutsch_jozsa",
        name: "Deutsch-Jozsa",
        category: "Oracle-Based",
        
        problem: "Determining if a boolean function is constant or balanced",
        math: "Phase Kickback & Quantum Parallelism",
        timeQuantum: "O(1) queries",
        timeClassical: "O(2^{n-1} + 1) queries",
        spaceQuantum: "O(n)",
        spaceClassical: "O(1)",
        classicalEq: "Iterative evaluation",
        qubitsReq: "n + 1",
        depth: "O(1) + Oracle depth",
        oracle: true,
        qft: false,
        qpe: false,
        applications: ["Demonstration of quantum supremacy for specific black-box problems"],
        advantages: ["Provides a clear, exact exponential speedup over classical deterministic"],
        limitations: ["No real-world practical application"],

        speedupType: "Exponential (over deterministic)",
        gateCount: "O(n)",
        scalingFnQ: (n) => 1,
        scalingFnC: (n) => Math.pow(2, n-1) + 1,

        ibm: "Very High",
        ionq: "Very High",
        quantinuum: "Very High",
        rigetti: "Very High",
        nativeGates: "H, Oracle gates",
        minLogical: "n+1",
        estPhysical: "10+",
        nisq: "Highly Feasible",
        faultTolerant: "Educational"
    },
    "simon": {
        id: "simon",
        name: "Simon's Algorithm",
        category: "Oracle-Based",
        
        problem: "Finding a hidden bitstring s where f(x) = f(x ⊕ s)",
        math: "Hadamard transforms and linear equation solving",
        timeQuantum: "O(n) queries",
        timeClassical: "O(2^{n/2}) queries",
        spaceQuantum: "O(n)",
        spaceClassical: "O(n)",
        classicalEq: "Collision finding (Birthday Paradox)",
        qubitsReq: "2n",
        depth: "O(n) + Oracle",
        oracle: true,
        qft: false,
        qpe: false,
        applications: ["Breaking symmetric cryptography (e.g. Even-Mansour)"],
        advantages: ["First algorithm to prove exponential separation relative to an oracle"],
        limitations: ["Requires O(n) classical post-processing (Gaussian elimination)"],

        speedupType: "Exponential",
        gateCount: "O(n)",
        scalingFnQ: (n) => Math.log2(n),
        scalingFnC: (n) => Math.pow(2, Math.log2(n)/2),

        ibm: "High",
        ionq: "High",
        quantinuum: "High",
        rigetti: "Medium",
        nativeGates: "H, Oracle structure",
        minLogical: "2n",
        estPhysical: "100+",
        nisq: "Moderate",
        faultTolerant: "Proof of Concept"
    }
};

window.AQCA_ALGORITHMS = AQCA_ALGORITHMS;
